name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token: # change this
    required: true
    description: 'GitHub auth token'
    default: '${{ secrets.WINGET_TOKEN }}'
runs:
  using: 'node12'
  main: 'dist/index.js'
